data:
    resource: "@DataBundle/Controller/"
    type:     annotation
    prefix:   /data/

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /users/

app:
    resource: '@AppBundle/Controller/'
    type: annotation
