transcript:
    resource: "@TranscriptBundle/Controller/"
    type:     annotation
    prefix:   /transcript/

data:
    resource: "@DataBundle/Controller/"
    type:     annotation
    prefix:   /data/

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /users/

app:
    resource: '@AppBundle/Controller/'
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc