comment:
    resource: "@CommentBundle/Controller/"
    type:     annotation
    prefix:   /

download:
    resource: "@DownloadBundle/Controller/"
    type:     annotation
    prefix:   /download/file/

user:
    resource: "@UserBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_comment_api:
    type: rest
    resource: "@CommentBundle/Resources/config/routing.yml"
    prefix: /
    defaults: { _format: html }

data-interface:
    type:     rest
    resource: AppBundle\Controller\DataInterfaceController

app-preferences:
    type:     rest
    resource: AppBundle\Controller\AppPreferenceController

override-thread:
    type:     rest
    resource: AppBundle\Controller\OverrideThreadController

entities:
    type:     rest
    resource: AppBundle\Controller\EntityController

resources:
    type:     rest
    resource: AppBundle\Controller\ResourceController

wills:
    type:     rest
    resource: AppBundle\Controller\WillController

will-types:
    type:     rest
    resource: AppBundle\Controller\WillTypeController

testators:
    type:     rest
    resource: AppBundle\Controller\TestatorController

places:
    type:     rest
    resource: AppBundle\Controller\PlaceController

place-names:
    type:     rest
    resource: AppBundle\Controller\PlaceNameController

military-units:
    type:     rest
    resource: AppBundle\Controller\MilitaryUnitController

hosting-organizations:
    type:     rest
    resource: AppBundle\Controller\HostingOrganizationController

transcripts:
    type:     rest
    resource: AppBundle\Controller\TranscriptController

transcript-logs:
    type:     rest
    resource: AppBundle\Controller\TranscriptLogController

comment-logs:
    type:     rest
    resource: AppBundle\Controller\CommentLogController

reference-items:
    type:     rest
    resource: AppBundle\Controller\ReferenceItemController

printed-references:
    type:     rest
    resource: AppBundle\Controller\PrintedReferenceController

manuscript-references:
    type:     rest
    resource: AppBundle\Controller\ManuscriptReferenceController

notes:
    type:     rest
    resource: AppBundle\Controller\NoteController

contents:
    type:     rest
    resource: AppBundle\Controller\ContentController

training-contents:
    type:     rest
    resource: AppBundle\Controller\TrainingContentController

training-results:
    type:     rest
    resource: AppBundle\Controller\TrainingResultController

media-contents:
    type:     rest
    resource: AppBundle\Controller\MediaContentController

contact:
    type:     rest
    resource: AppBundle\Controller\ContactController

XML:
    type:     rest
    resource: AppBundle\Controller\XMLController

logs:
    type:     rest
    resource: AppBundle\Controller\LogsController

model:
    type:     rest
    resource: AppBundle\Controller\ModelController

users:
    type:     rest
    resource: UserBundle\Controller\UserController

preferences:
    type:     rest
    resource: UserBundle\Controller\PreferenceController

accesses:
    type:     rest
    resource: UserBundle\Controller\AccessController

iiif-manifests:
    type:     rest
    resource: AppBundle\Controller\IIIFManifestController

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"