user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /users/

app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

entities:
    type:     rest
    resource: AppBundle\Controller\EntityController

resources:
    type:     rest
    resource: AppBundle\Controller\ResourceController

wills:
    type:     rest
    resource: AppBundle\Controller\WillController

testators:
    type:     rest
    resource: AppBundle\Controller\TestatorController

transcripts:
    type:     rest
    resource: AppBundle\Controller\TranscriptController