download:
    resource: "@DownloadBundle/Controller/"
    type:     annotation
    prefix:   /download/file/

user:
    resource: "@UserBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /
    defaults: { _format: html }

app-preferences:
    type:     rest
    resource: AppBundle\Controller\AppPreferenceController

override-thread:
    type:     rest
    resource: AppBundle\Controller\ThreadController

entities:
    type:     rest
    resource: AppBundle\Controller\EntityController

resources:
    type:     rest
    resource: AppBundle\Controller\ResourceController

wills:
    type:     rest
    resource: AppBundle\Controller\WillController

testators:
    type:     rest
    resource: AppBundle\Controller\TestatorController

places:
    type:     rest
    resource: AppBundle\Controller\PlaceController

military-units:
    type:     rest
    resource: AppBundle\Controller\MilitaryUnitController

transcripts:
    type:     rest
    resource: AppBundle\Controller\TranscriptController

contents:
    type:     rest
    resource: AppBundle\Controller\ContentController

contact:
    type:     rest
    resource: AppBundle\Controller\ContactController

XML:
    type:     rest
    resource: AppBundle\Controller\XMLController

logs:
    type:     rest
    resource: AppBundle\Controller\LogsController

model:
    type:     rest
    resource: AppBundle\Controller\ModelController

users:
    type:     rest
    resource: UserBundle\Controller\UserController

preferences:
    type:     rest
    resource: UserBundle\Controller\PreferenceController

accesses:
    type:     rest
    resource: UserBundle\Controller\AccessController

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"