user:
    resource: "@UserBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /
    defaults: { _format: html }

entities:
    type:     rest
    resource: AppBundle\Controller\EntityController

resources:
    type:     rest
    resource: AppBundle\Controller\ResourceController

wills:
    type:     rest
    resource: AppBundle\Controller\WillController

testators:
    type:     rest
    resource: AppBundle\Controller\TestatorController

transcripts:
    type:     rest
    resource: AppBundle\Controller\TranscriptController

contents:
    type:     rest
    resource: AppBundle\Controller\ContentController

users:
    type:     rest
    resource: UserBundle\Controller\UserController

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"