security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    role_hierarchy:
        ROLE_TAXONOMY_EDIT:  ROLE_USER
        ROLE_MODO:            ROLE_USER, ROLE_TAXONOMY_EDIT
        ROLE_ADMIN:           ROLE_MODO, ROLE_TAXONOMY_EDIT
        ROLE_SUPER_ADMIN:     ROLE_ADMIN, ROLE_MODO, ROLE_TAXONOMY_EDIT

    firewalls:
        oauth_token:  # Everyone can access the access token URL.
            pattern: ^/oauth/v2/token
            security: false
        api:
            pattern: ^/        # All URLs are protected
            fos_oauth: true    # OAuth2 protected resource
            stateless: true    # Do no set session cookies
            anonymous: true