services:
    user.form.registration:
        class: UserBundle\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: user_registration }
        arguments:
            - '%fos_user.model.user.class%'

    user.form.profile:
        class: UserBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: user_profile }
    user.user:
        class: UserBundle\Services\User
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@app.versioning'
    user.listener.registration:
        class: UserBundle\EventListener\RegistrationListener
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@user.user'
        tags:
            - { name: kernel.event_subscriber }
    user.listener.change_password:
        class: UserBundle\EventListener\ChangePasswordListener
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@twig"
            - "@mailer"
        tags:
            - { name: kernel.event_subscriber }
    user.listener.reset_password:
        class: UserBundle\EventListener\ResetPasswordListener
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@twig"
            - "@mailer"
        tags:
            - { name: kernel.event_subscriber }