services:
    app.entity:
        class: AppBundle\Services\Entity
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@app.will'
            - '@app.resourcei'

    app.resourcei:
        class: AppBundle\Services\ResourceI
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@app.transcript'

    app.testator:
        class: AppBundle\Services\Testator
        arguments:
            - '@doctrine.orm.entity_manager'

    app.place:
        class: AppBundle\Services\Place
        arguments:
            - '@doctrine.orm.entity_manager'

    app.militaryUnit:
        class: AppBundle\Services\MilitaryUnit
        arguments:
            - '@doctrine.orm.entity_manager'

    app.transcript:
        class: AppBundle\Services\Transcript
        arguments:
            - '@doctrine.orm.entity_manager'

    app.will:
        class: AppBundle\Services\Will
        arguments:
            - '@doctrine.orm.entity_manager'

    app.versioning:
        class: AppBundle\Services\Versioning
        arguments:
            - '@doctrine.orm.entity_manager'

    # Mailing
    app.contact:
        class: AppBundle\Services\Contact
        arguments:
            - '@mailer'

    # XML Management
    app.xml.builder:
        class: AppBundle\Services\XML\Builder
        arguments:
            - '@doctrine.orm.entity_manager'
    app.xml.validator:
        class: AppBundle\Services\XML\Validator
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@app.xml.builder'
            - '%validatorRelaxNG%'
    app.xml.model:
        class: AppBundle\Services\XML\Model
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%modelXML%'

    # Listeners
    app.listener.comment:
        class: AppBundle\EventListener\AuthorCommentListener
        arguments:
            - '@security.token_storage'
        tags:
            - { name: kernel.event_listener, event: fos_comment.comment.pre_persist, method: onCommentPrePersist }


    app.listener.will:
        class: AppBundle\EventListener\WillSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    #app.listener.entity:
    #    class: AppBundle\EventListener\EntitySubscriber
    #    tags:
    #        - { name: doctrine.event_subscriber, connection: default }

    # Commands
    app.command.test.email:
            class: AppBundle\Command\TestEmailCommand
            arguments:
                - '%mailer_user%'

